force-app/main/default/objects/Repositorio__c/Repositorio__c.object-meta.xml
<CustomObject>
    <label>Repositório</label>
    <nameField>
        <label>Nome do repositório</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositórios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repositorio__c/fields/Estrela__c.field-meta.xml
<CustomField>
    <fullName>Estrela__c</fullName>
    <label>Estrela</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/Fork__c.field-meta.xml
<CustomField>
    <fullName>Fork__c</fullName>
    <label>Fork</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>IdExterno</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RepositorioTest.cls
@isTest
private class RepositorioTest {
    @isTest
    static void buscarRepositorioTest(){
        StaticResourceCalloutMock objMock = new StaticResourceCalloutMock();
        objMock.setStaticResource('BuscaRepositorioMock');
        objMock.setStatusCode(200);
        
        Test.setMock(HttpCalloutMock.class, objMock);

        Test.startTest();
        RepositorioBO.atualizarRepositorios();
        Test.stopTest();

        System.assertEquals(2, 
            [
                SELECT
                    Id
                FROM Repositorio__c
            ].size()
        );
    }

    @isTest
    static void compartilharRepositorioTest(){
        Repositorio__c objRepositorio = new Repositorio__c(
            Name = 'Projeto teste',
            Estrela__c = 10,
            Fork__c = 5,
            IdExterno__c = 123
        );

        Test.startTest();
        insert objRepositorio;
        Test.stopTest();

        User objUsuario = UserDAO.buscarPorNome('Integration User');

        List<Repositorio__Share> lstCompartilhamento = [SELECT Id FROM Repositorio__Share WHERE ParentId = :objRepositorio.Id AND UserOrGroupId = :objUsuario.Id];

        System.assertEquals(1, lstCompartilhamento.size());
    }
}