force-app/main/default/objects/Repositorio__c/Repositorio__c.object-meta.xml
<CustomObject>
    <label>Repositório</label>
    <nameField>
        <label>Nome do repositório</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositórios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repositorio__c/fields/Estrela__c.field-meta.xml
<CustomField>
    <fullName>Estrela__c</fullName>
    <label>Estrela</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/Fork__c.field-meta.xml
<CustomField>
    <fullName>Fork__c</fullName>
    <label>Fork</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>IdExterno</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RepositorioBO.cls
public class RepositorioBO {
    @future(callout=true)
    public static void atualizarRepositorios() {
        List<RepositorioServiceTO.RepositorioTO> lstRepositorioTO = RepositorioService.buscarRepositorios();

        List<Repositorio__c> lstRepositorio = new List<Repositorio__c>();

        for (RepositorioServiceTO.RepositorioTO objRepositorioTO : lstRepositorioTO){
            lstRepositorio.add(
                new Repositorio__c(
                    Name = objRepositorioTO.name,
                    IdExterno__c = objRepositorioTO.id,
                    Estrela__c = objRepositorioTO.stargazers_count,
                    Fork__c = objRepositorioTO.forks_count
                )
            );
        }

        if (!lstRepositorio.isEmpty()){
            upsert lstRepositorio IdExterno__c;
        }
    }

    public static void compartilharRepositorios(List<Repositorio__c> lstRepositorios){
        List<Repositorio__Share> lstCompartilhamentos = new List<Repositorio__Share>();
        User objUsuario = UserDAO.buscarPorNome('Integration User');

        for (Repositorio__c objRepositorio : lstRepositorios){
            lstCompartilhamentos.add(
                new Repositorio__Share(
                    ParentId = objRepositorio.Id,
                    UserOrGroupId = objUsuario.Id,
                    AccessLevel = 'Edit'
                )
            );
        }

        insert lstCompartilhamentos;
    }
}