force-app/main/default/objects/Repositorio__c/Repositorio__c.object-meta.xml
<CustomObject>
    <label>Repositório</label>
    <nameField>
        <label>Nome do repositório</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositórios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repositorio__c/fields/Estrela__c.field-meta.xml
<CustomField>
    <fullName>Estrela__c</fullName>
    <label>Estrela</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/Fork__c.field-meta.xml
<CustomField>
    <fullName>Fork__c</fullName>
    <label>Fork</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>IdExterno</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ListagemRepositoriosTest.cls
@isTest
private class ListagemRepositoriosTest {
    @isTest
    static void buscarRepositorioTest(){
        insert new List<Repositorio__c>{
            new Repositorio__c(
                Name = 'Projeto teste',
                Estrela__c = 10,
                Fork__c = 5,
                IdExterno__c = 123
            )
        };

        Test.startTest();
        List<ListagemRepositoriosController.RepositorioTO> lstRepositorio = ListagemRepositoriosController.buscarRepositorios();
        Test.stopTest();

        System.assertEquals(1, lstRepositorio.size());
    }
}