force-app/main/default/objects/Repositorio__c/Repositorio__c.object-meta.xml
<CustomObject>
    <label>Repositório</label>
    <nameField>
        <label>Nome do repositório</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositórios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repositorio__c/fields/Estrela__c.field-meta.xml
<CustomField>
    <fullName>Estrela__c</fullName>
    <label>Estrela</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/Fork__c.field-meta.xml
<CustomField>
    <fullName>Fork__c</fullName>
    <label>Fork</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repositorio__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>IdExterno</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ListagemRepositoriosController.cls
public class ListagemRepositoriosController {
    @AuraEnabled
    public static List<RepositorioTO> buscarRepositorios(){
        try {
            List<Repositorio__c> lstRepositorio = RepositorioDAO.buscarRepositorios();

            List<RepositorioTO> lstRepositorioTO = new List<RepositorioTO>();

            for (Repositorio__c objRepositorio : lstRepositorio){
                RepositorioTO objRepositorioTO = new RepositorioTO();

                objRepositorioTO.Id = objRepositorio.Id;
                objRepositorioTO.IdExterno = objRepositorio.IdExterno__c;
                objRepositorioTO.Link = URL.getSalesforceBaseUrl().getHost() + '/' + objRepositorio.Id;
                objRepositorioTO.Nome = objRepositorio.Name;
                objRepositorioTO.Estrelas = objRepositorio.Estrela__c;
                objRepositorioTO.Forks = objRepositorio.Fork__c;

                lstRepositorioTO.add(objRepositorioTO);
            }

            return lstRepositorioTO;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class RepositorioTO {
        @AuraEnabled
        public Id Id { get; set; }

        @AuraEnabled
        public Decimal IdExterno { get; set; }

        @AuraEnabled
        public String Link { get; set; }

        @AuraEnabled
        public String Nome { get; set; }

        @AuraEnabled
        public Decimal Estrelas { get; set; }

        @AuraEnabled
        public Decimal Forks { get; set; }
    }
}